server:
  port: 8082
spring:
  application:
    name: flight-service
  cloud:
    function:
      definition: flightProcessor
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      bindings:
        flightProcessor-in-0:
          destination: ${topics.appointment-requested:appointments.requested}
          content-type: application/json
        flightProcessor-out-0:
          destination: ${topics.flight-reserved:flight.reserved}
          content-type: application/json
management:
  endpoints:
    web:
      exposure:
        include: "*"

topics:
  appointment-requested: appointments.requested
  flight-reserved: flight.reserved
