server:
  port: 8084
spring:
  application:
    name: billing-service
  cloud:
    function:
      definition: flightReservedConsumer;hotelReservedConsumer;billingChargedSupplier;sagaCompletedSupplier
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      bindings:
        flightReservedConsumer-in-0:
          destination: ${topics.flight-reserved:flight.reserved}
          content-type: application/json
        hotelReservedConsumer-in-0:
          destination: ${topics.hotel-reserved:hotel.reserved}
          content-type: application/json
        billingChargedSupplier-out-0:
          destination: ${topics.billing-charged:billing.charged}
          content-type: application/json
        sagaCompletedSupplier-out-0:
          destination: ${topics.saga-completed:saga.completed}
          content-type: application/json
management:
  endpoints:
    web:
      exposure:
        include: "*"

topics:
  flight-reserved: flight.reserved
  hotel-reserved: hotel.reserved
  billing-charged: billing.charged
  saga-completed: saga.completed
