server:
  port: 8083
spring:
  application:
    name: hotel-service
  cloud:
    function:
      definition: hotelProcessor
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      bindings:
        hotelProcessor-in-0:
          destination: ${topics.appointment-requested:appointments.requested}
          content-type: application/json
        hotelProcessor-out-0:
          destination: ${topics.hotel-reserved:hotel.reserved}
          content-type: application/json
management:
  endpoints:
    web:
      exposure:
        include: "*"

topics:
  appointment-requested: appointments.requested
  hotel-reserved: hotel.reserved
