server:
  port: 8081
spring:
  application:
    name: appointment-service
  cloud:
    function:
      definition: appointmentRequestedSupplier
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      poller:
        fixed-delay: 200
      bindings:
        appointmentRequestedSupplier-out-0:
          destination: ${topics.appointment-requested:appointments.requested}
          content-type: application/json
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Temas por defecto
topics:
  appointment-requested: appointments.requested
